### ISSUE TITLE
Error on Webpack 4.0: DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

### ISSUE THREAD

**Issue by guilhermebruzzi** [theGC/html-webpack-inline-svg-plugin#17]
Using on `package.json`:

```js
...
"webpack": "^4.15.1",
"html-webpack-plugin": "^3.2.0",
"html-webpack-inline-svg-plugin": "^1.2.4",
```

On `webpack.config.babel.js`:

```js
import HtmlWebpackInlineSVGPlugin from 'html-webpack-inline-svg-plugin'

// ...
new HtmlWebpackPlugin({
          inject: true,
          template: path.join(__dirname, 'src/index.html'),
        }),
new HtmlWebpackInlineSVGPlugin({
          runPreEmit: true,
        }),

```

Full stacktrace of the error when running `webpack-dev-server --hot`:

```
node:69945) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at HtmlWebpackInlineSVGPlugin.apply (/Users/guilhermebruzzi/projetos/vtex/checkout-instore/node_modules/html-webpack-inline-svg-plugin/index.js:44:18)
    at webpack (/Users/guilhermebruzzi/projetos/vtex/checkout-instore/node_modules/webpack/lib/webpack.js:37:12)
    at startDevServer (/Users/guilhermebruzzi/projetos/vtex/checkout-instore/node_modules/webpack-dev-server/bin/webpack-dev-server.js:379:16)
    at processOptions (/Users/guilhermebruzzi/projetos/vtex/checkout-instore/node_modules/webpack-dev-server/bin/webpack-dev-server.js:361:5)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
    at Function.Module.runMain (module.js:692:11)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
```

**Comment by captbaritone** [comment]
Looks like there is a migration guide here: https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202 Someone will need to upgrade this package to use the new API.

**Comment by theGC** [comment]
sorted with v2.x.x
