### ISSUE TITLE
ENOENT: File not found with `webpack serve`

### ISSUE THREAD

**Issue by MuhammadSawalhy** [theGC/html-webpack-inline-svg-plugin#38]
When building for production, everything is good, but my SVGs are not inlined when serving with `webpack serve`.

The error:

```
[Error: ENOENT: no such file or directory, open '/home/ms/Desktop/myp/gem/client/public/assets/search.20163530b246508606e2120e1a9dc8fb.svg'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/ms/Desktop/myp/gem/client/public/assets/search.20163530b246508606e2120e1a9dc8fb.svg'
}
TypeError: this.html.charCodeAt is not a function
    at Preprocessor.advance (/home/ms/Desktop/myp/gem/client/node_modules/parse5/lib/tokenizer/preprocessor.js:106:28)
    at Tokenizer._consume (/home/ms/Desktop/myp/gem/client/node_modules/parse5/lib/tokenizer/index.js:292:34)
    at Tokenizer.getNextToken (/home/ms/Desktop/myp/gem/client/node_modules/parse5/lib/tokenizer/index.js:253:29)
    at Parser._runParsingLoop (/home/ms/Desktop/myp/gem/client/node_modules/parse5/lib/parser/index.js:422:42)
    at Parser.parseFragment (/home/ms/Desktop/myp/gem/client/node_modules/parse5/lib/parser/index.js:372:14)
    at Object.parseFragment (/home/ms/Desktop/myp/gem/client/node_modules/parse5/lib/index.js:22:19)
    at /home/ms/Desktop/myp/gem/client/node_modules/html-webpack-inline-svg-plugin/index.js:321:45
    at new Promise (<anonymous>)
    at HtmlWebpackInlineSVGPlugin.processImage (/home/ms/Desktop/myp/gem/client/node_modules/html-webpack-inline-svg-plugin/index.js:316:16)
    at /home/ms/Desktop/myp/gem/client/node_modules/html-webpack-inline-svg-plugin/index.js:299:33
TypeError: this.html.charCodeAt is not a function
    at Preprocessor.advance (/home/ms/Desktop/myp/gem/client/node_modules/parse5/lib/tokenizer/preprocessor.js:106:28)
    at Tokenizer._consume (/home/ms/Desktop/myp/gem/client/node_modules/parse5/lib/tokenizer/index.js:292:34)
    at Tokenizer.getNextToken (/home/ms/Desktop/myp/gem/client/node_modules/parse5/lib/tokenizer/index.js:253:29)
    at Parser._runParsingLoop (/home/ms/Desktop/myp/gem/client/node_modules/parse5/lib/parser/index.js:422:42)
    at Parser.parseFragment (/home/ms/Desktop/myp/gem/client/node_modules/parse5/lib/parser/index.js:372:14)
    at Object.parseFragment (/home/ms/Desktop/myp/gem/client/node_modules/parse5/lib/index.js:22:19)
    at /home/ms/Desktop/myp/gem/client/node_modules/html-webpack-inline-svg-plugin/index.js:321:45
    at new Promise (<anonymous>)
    at HtmlWebpackInlineSVGPlugin.processImage (/home/ms/Desktop/myp/gem/client/node_modules/html-webpack-inline-svg-plugin/index.js:316:16)
    at /home/ms/Desktop/myp/gem/client/node_modules/html-webpack-inline-svg-plugin/index.js:299:33
```

**Comment by AntonioRedondo** [comment]
This is a duplicated of https://github.com/theGC/html-webpack-inline-svg-plugin/issues/19.

Please check https://github.com/theGC/html-webpack-inline-svg-plugin/issues/19#issuecomment-548639977 to make `html-webpack-inline-svg-plugin` working with `webpack-dev-server`.
